main: main.o
	gcc $$CFLAGS $$LDFLAGS -lnative -lwiringPi $^ -o $@

prueba_lncurses:

	gcc $$CFLAGS $$LDFLAGS -lnative -lwiringPi prueba_lncurses.c -lncurses -o prueba_lncurses

%: %.c
	gcc $$CFLAGS $$LDFLAGS -lnative -lwiringPi $^ -c $@


